name: Feature request
description: Suggest an idea or a site that should be supported
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like
      description: The problem you're trying to solve and how you'd like it to work.
    validations:
      required: true
